server:
  port: 80

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tripj?serverTimezone=Asia/Seoul
      username:
      password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        use_sql_comments: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000



springdoc:
  packages-to-scan: com.tripj
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui: #http://localhost:8080/swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true


